### ISSUE TITLE
ERROR diffusion_model.input_blocks

### ISSUE THREAD

**Issue by ponponych** [shiimizu/ComfyUI-PhotoMaker-Plus#14]
Some ERRORS started out of nowhere
\ComfyUI>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build --lowvram --force-fp16
** Platform: Windows
** Python version: 3.11.6
Queue prompt... and this:
![2024-01-23_124323](https://github.com/shiimizu/ComfyUI-PhotoMaker/assets/120938885/a704d867-9eac-4624-bd91-91eaa35e3187)

**Comment by shiimizu** [comment]
Are you perhaps using an SD1.5 LoRa somewhere?

**Comment by ponponych** [comment]
I downloaded the update, now this
![2024-01-23_130425](https://github.com/shiimizu/ComfyUI-PhotoMaker/assets/120938885/f43d97b2-a42d-432e-9b15-6aaf465551e5)

**Comment by shiimizu** [comment]
That looks like a previous version of the node. Make sure you're up-to-date and then you can try the workflow in the README.

**Comment by ponponych** [comment]
I can't find the workflow anywhere
