### ISSUE TITLE
Can't get similar image

### ISSUE THREAD

**Issue by jesenzhang** [shiimizu/ComfyUI-PhotoMaker-Plus#16]
The workflow with the same parameter but different input image , the result for asian is not  good。
![斯嘉丽](https://github.com/shiimizu/ComfyUI-PhotoMaker/assets/7984556/22bfa1ac-0d05-45a4-9cce-b7e0b7f16ea1)
![热巴](https://github.com/shiimizu/ComfyUI-PhotoMaker/assets/7984556/898807cd-45f1-42d5-9708-92d28411160f)

**Comment by koko93s** [comment]
Unless I'm missing something, this is a workflow for FaceID V2 for IPadapter and you've posted it on the PhotoMaker repository.

**Comment by jesenzhang** [comment]
> Unless I'm missing something, this is a workflow for FaceID V2 for IPadapter and you've posted it on the PhotoMaker repository.

Yes, The only response is letting me to try InstantID.

**Comment by jesenzhang** [comment]
> Unless I'm missing something, this is a workflow for FaceID V2 for IPadapter and you've posted it on the PhotoMaker repository.

My mistake, ipadapter faceid has the same issuse.

**Comment by koko93s** [comment]
@jesenzhang if it makes you feel any better, I don't think the output if very good for non-famous white people either.  I have a generic pretty girl and the reseult is not perfect.  It makes her face skinnier, changes the shape of her eyes, etc.  It's close, but not a perfect match.

**Comment by smthemex** [comment]
photomaker官方推荐的是：在关键词里加入 类似Asian women face 一类的限定词 。试试我这个工作流（comfyui原生支持photomaker 加上shiimizu这个节点）
![workflow](https://github.com/shiimizu/ComfyUI-PhotoMaker-Plus/assets/138738845/439c12c0-5122-4c77-b0c5-d7ac35c6c023)

**Comment by jesenzhang** [comment]
> photomaker官方推荐的是：在关键词里加入 类似Asian women face 一类的限定词 。试试我这个工作流（comfyui原生支持photomaker 加上shiimizu这个节点） ![workflow](https://private-user-images.githubusercontent.com/138738845/301444137-439c12c0-5122-4c77-b0c5-d7ac35c6c023.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4MzQxNDIsIm5iZiI6MTcwNjgzMzg0MiwicGF0aCI6Ii8xMzg3Mzg4NDUvMzAxNDQ0MTM3LTQzOWMxMmMwLTUxMjItNGM3Ny1iMGM1LWQ3YWMzNWM2YzAyMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwMlQwMDMwNDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMGNlMjE2OWJhYmM4NGQ0NmZhMzI4MGQ0YzA1Y2Y0OGQ0NDg2ZDYyNGM5ODM4ZTQ0MzAzYjRmMWJhMzgzNjUyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.r8vYrzqXZS9Jcsnx_iIk3I_T8GN09fWbS2zUAiEdnkw)
试过了，也差不多的结果，还是用InstantID吧
![image](https://github.com/shiimizu/ComfyUI-PhotoMaker-Plus/assets/7984556/63e9d1de-42d6-45e4-add6-7b48adccfd10)

**Comment by flankechen** [comment]
same here, really difficult to get high identity face gen for asian girls.

**Comment by shiimizu** [comment]
Closing this since V2 solved this issue. There are also workflows available at https://github.com/shiimizu/ComfyUI-PhotoMaker-Plus/tree/main/examples.
