### ISSUE TITLE
Workflow JSON Missing

### ISSUE THREAD

**Issue by mike-rowley** [shiimizu/ComfyUI-PhotoMaker-Plus#21]
Where is the Workflow JSON file? It doesnt seem to be anywhere in the readme.  I am specifically looking for a workflow that uses the new PhotoMaker Encode Plus.

**Comment by shiimizu** [comment]
It’s in the image in the readme. Download that and drag and drop it into comfyui.

**Comment by mike-rowley** [comment]
WOW that is the MOST non-intuitive process I have ever seen in 30 years of software development.  Thanks.
