### ISSUE TITLE
ModelPatcher error

### ISSUE THREAD

**Issue by supereth** [shiimizu/ComfyUI-PhotoMaker-Plus#24]
I am getting the following error:

Error occurred when executing PhotoMakerAdapter_Loader_local:

'ModelPatcher' object has no attribute 'load_photomaker_adapter'

Full path is properly entered in the pm_model_path and file nale properly set to photomaker-v1.bin

ComfyUI properly updated, all photomaker as well.

Any ideas of what might be causing the problem?

**Comment by supereth** [comment]
Looks like I was using the wrong node, but now i get a new error msg:

Error occurred when executing PhotoMakerAdapter_Loader_local:

Error(s) in loading state_dict for PhotoMakerIDEncoder:
Missing key(s) in state_dict: "vision_model.embeddings.position_ids".

**Comment by shiimizu** [comment]
This repo does not have that node `PhotoMakerAdapter_Loader_local`.

**Comment by supereth** [comment]
I must be mixing then some nodes from the ZHO fork, will try to restart everything using just this repo, thanks for the help!
