### ISSUE TITLE
Is there a link somewhere to an example worfklow ?

### ISSUE THREAD

**Issue by HeavyTony2** [shiimizu/ComfyUI-PhotoMaker-Plus#27]
I'm not sure how to use the nodes since there's neither clear documentation on this repo nor an example workflow.

**Comment by bigcat88** [comment]
Example is in the Readme.. 
https://private-user-images.githubusercontent.com/54494639/299515843-a8320460-a8e0-46df-9780-66a70631e989.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk0NTA1MzEsIm5iZiI6MTcwOTQ1MDIzMSwicGF0aCI6Ii81NDQ5NDYzOS8yOTk1MTU4NDMtYTgzMjA0NjAtYThlMC00NmRmLTk3ODAtNjZhNzA2MzFlOTg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAzVDA3MTcxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzYmNlYjUzZWE1N2MyNGIyOTliYWVmMjMwZTZlNTE3NDMzMWM0OTc3YTBhMTVhODY1ZmQ2MTQ2ZTM0YzhhNzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.g6G1VObuVLK05qBxHMet7rnaq6vS74BnA_DM73NZXDM

**Comment by HeavyTony2** [comment]
@bigcat88 That's a picture, not a json file. Are saying there's workflow hidden in the metadata?

**Comment by FXSensor** [comment]
> Ok, I found the workflow in the metadata.

Can you share an example, please?

**Comment by bigcat88** [comment]
> Example is in the Readme.. https://private-user-images.githubusercontent.com/54494639/299515843-a8320460-a8e0-46df-9780-66a70631e989.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk0NTA1MzEsIm5iZiI6MTcwOTQ1MDIzMSwicGF0aCI6Ii81NDQ5NDYzOS8yOTk1MTU4NDMtYTgzMjA0NjAtYThlMC00NmRmLTk3ODAtNjZhNzA2MzFlOTg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAzVDA3MTcxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzYmNlYjUzZWE1N2MyNGIyOTliYWVmMjMwZTZlNTE3NDMzMWM0OTc3YTBhMTVhODY1ZmQ2MTQ2ZTM0YzhhNzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.g6G1VObuVLK05qBxHMet7rnaq6vS74BnA_DM73NZXDM

drag this image into a ComfyUI

**Comment by bigcat88** [comment]
In this repo's Readme: "Example workflow that you can load in ComfyUI." - on top of this text there is an image.

**Comment by shiimizu** [comment]
https://github.com/shiimizu/ComfyUI-PhotoMaker-Plus/tree/main/examples
