### ISSUE TITLE
Can we have a simpler workflow example?

### ISSUE THREAD

**Issue by pandayummy** [shiimizu/ComfyUI-PhotoMaker-Plus#29]
The workflow example provided is a little complex, can we have a simpler one?

**Comment by shiimizu** [comment]
See `https://github.com/comfyanonymous/ComfyUI/issues/2650#issuecomment-1913472632`

**Comment by shiimizu** [comment]
See `https://github.com/comfyanonymous/ComfyUI/issues/2650#issuecomment-1913472632`
That image can be loaded as a workflow.

**Comment by shiimizu** [comment]
See https://github.com/shiimizu/ComfyUI-PhotoMaker-Plus/blob/main/examples/v2-simple-workflow.json
and https://github.com/shiimizu/ComfyUI-PhotoMaker-Plus/tree/main/examples
