### ISSUE TITLE
v2 is released!

### ISSUE THREAD

**Issue by ke1ne** [shiimizu/ComfyUI-PhotoMaker-Plus#31]
https://github.com/TencentARC/PhotoMaker

**Comment by shiimizu** [comment]
It's very good! I tried their [demo](https://huggingface.co/spaces/TencentARC/PhotoMaker-V2) and it can do Asian faces well!

**Comment by camoody1** [comment]
@shiimizu Thank you for adding this to your update list! I look forward to giving v2 a try!

**Comment by NeoAnthropocene** [comment]
It is currently broken in the ComfyUI.
[Check here ](https://huggingface.co/TencentARC/PhotoMaker-V2/discussions/2)for the details.

**Comment by camoody1** [comment]
> It is currently broken in the ComfyUI. [Check here ](https://huggingface.co/TencentARC/PhotoMaker-V2/discussions/2)for the details.

Which is why @shiimizu will need to update his nodes.

**Comment by Falkonar** [comment]
Thank you for adding InsightFace Loader. Can you please provide workflow how to use V2 model in ComfyUI? The one you add to commit for v1

**Comment by Willy-Shenn** [comment]
Sorry, so does this mean that this node cannot be used with the v2 model yet?

**Comment by camoody1** [comment]
> Sorry, so does this mean that this node cannot be used with the v2 model yet?

It looks like the developer just added two new commits to his code today. Just keep updating the node pack. It will support v2 soon enough.

**Comment by shiimizu** [comment]
It's one commit, I just redid an earlier one. With that [commit](https://github.com/shiimizu/ComfyUI-PhotoMaker-Plus/commit/7bdd98392830bc2aa1b9ae0ce4fe55a02146a5cf), the v2 model is supported. Please take a look at the [installation](https://github.com/shiimizu/ComfyUI-PhotoMaker-Plus#installation) instructions again.

**Comment by camoody1** [comment]
> It's one commit, I just redid an earlier one. With that [commit](https://github.com/shiimizu/ComfyUI-PhotoMaker-Plus/commit/7bdd98392830bc2aa1b9ae0ce4fe55a02146a5cf), the v2 model is supported. Please take a look at the [installation](https://github.com/shiimizu/ComfyUI-PhotoMaker-Plus#installation) instructions again.

Excellent! Thank you for your quick work! Have a great weekend.

**Comment by camoody1** [comment]
@shiimizu Any sample workflows available? 😁

**Comment by shiimizu** [comment]
See https://github.com/shiimizu/ComfyUI-PhotoMaker-Plus/blob/main/examples/v2-workflow.json

**Comment by Paper99** [comment]
Thanks for your support ❤️

**Comment by KINGLIFER** [comment]
Did anyone else get this error?

'builtin_function_or_method' object has no attribute 'warning'
