### ISSUE TITLE
What's the correct way to load the photomaker lora?

### ISSUE THREAD

**Issue by deepfree2023** [shiimizu/ComfyUI-PhotoMaker-Plus#32]
It's a bit confusing how to load the photomaker lora in the description:

1. Load the LoRA within the model using the LoraLoaderModelOnly node.
2. Automatic PhotoMaker LoRA detection and loading in the LoraLoader nodes.

I wonder what's the correct way to load the photomaker lora, 1 or 2 or 1&2?

**Comment by deepfree2023** [comment]
And any recommendation on the lora strength value of 1?

**Comment by shiimizu** [comment]
Technically, the model isn't a LoRA but contains one:
>It mainly contains two parts corresponding to two keys in loaded state dict: <sup>[1](https://huggingface.co/TencentARC/PhotoMaker-V2#model-details)</sup>
>1. `id_encoder` includes finetuned OpenCLIP-ViT-H-14 and a few fuse layers.
>2. `lora_weights` applies to all attention layers in the UNet, and the rank is set to 64.

I made a hacky way so that the LoraLoader nodes could load the lora inside the model without having you extract it manually beforehand. So it's as simple as downloading the model into the `ComfyUI/models/photomaker` folder, and that's it.

As for the lora, load one or the other. I think the lora strength should be kept >= 0.5. What's more important is the style strength (as seen in the [example workflow](https://github.com/shiimizu/ComfyUI-PhotoMaker-Plus/blob/main/examples/v2-workflow.json) ).

**Comment by deepfree2023** [comment]
Thank you for the example workflow! 😁

It's clear that the PhotoMaker model should be loaded twice, both in the LoraLoaderModelOnly and PhotoMaker Loader (plus) nodes.

I believe the "prep image for CLIP vision" and "style strength ratio" are no longer necessary in the V2 workflow. InsightFace can support large input images, detect face positions, and extract facial key points. The "prep image for CLIP vision" always scales the input image to 224x224, which results in a significant loss of information. By using high-resolution input images, V2 with a single KSampler (without style strength ratio) can produce much better results than V1. The style strength ratio doesn't seem to offer any further improvement.

**Comment by deepfree2023** [comment]
A remaining issue is that the similarity of V2 results seems much lower compared to the official Hugging Face space demo.

**Comment by klossm** [comment]
> 剩下的问题是，与官方的 Hugging Face 空间演示相比，V2 结果的相似度似乎要低得多。

I also found it much weaker than the official Hugging Face space demo.

**Comment by shiimizu** [comment]
Right. So what's more important is the number of high quality reference images and the sdxl checkpoint. The style strength ratio helps with applying styles like line art. I agree that the PrepImage nodes can be omitted.

For example, I used 31 references and I got a good output. That’s probably too much, but the more, the better. I'll upload improved workflows later.

**Comment by klossm** [comment]
![20240728060916](https://github.com/user-attachments/assets/dc316edf-6c18-417e-bf1c-324d4ce52a16)
![6153527](https://github.com/user-attachments/assets/34339757-c524-4016-a8ce-3b53a420e973)

In this case I only used a reference image in the Hugging Face space demo, which I tried to reproduce in comfyui, but the result was never achieved!Above is the image I used and the output image result

**Comment by klossm** [comment]
> Right. So what's more important is the number of high quality reference images and the sdxl checkpoint. The style strength ratio helps with applying styles like line art. I agree that the PrepImage nodes can be omitted.
> 
> For example, I used 31 references and I got a good output. That’s probably too much, but the more, the better. I'll upload improved workflows later.

![20240728060916](https://github.com/user-attachments/assets/dc316edf-6c18-417e-bf1c-324d4ce52a16)
![6153527](https://github.com/user-attachments/assets/34339757-c524-4016-a8ce-3b53a420e973)

In this example, I only used the single reference image from the official Hugging Face space demo {I used the default parameters}, which I tried to replicate in comfyui{The RealVisXL-V4-V4-BakedVAE model was used}, But the results were not good.The image above shows the image I used and the result of the output image. The clarity of this reference image isn't even very good.

For the images output from the official Hugging Face space demo, I used Face Embeds Distance for the calculation, where dist is below 0.4
![20240728062555](https://github.com/user-attachments/assets/565b3dce-73f3-4d9b-b4fa-2b4ebf417ebe)

**Comment by shiimizu** [comment]
Thanks for the report. There does seem to be an issue. I'm not sure where, but I'll investigate.

**Comment by klossm** [comment]
Could the problem be due to the sampler? Would the result be different if the original sampler of diffusers was used，Using a sampler combination like deis beta seems to work better, but has limited effect.

**Comment by deepfree2023** [comment]
The results of V2 seem to indicate that there can sometimes be significant differences between similarity algorithms and human visual consistency judgments. For example, when using Insightface to detect feature points and cosine to calculate similarity, the value for InstantID might be much lower than that of V2. However, at first glance, the V2 image may feels more similar.

**Comment by deepfree2023** [comment]
InstantID and PuLID use Insightface's antelopev2 model, while V2 uses Insightface's buffalo_l model. The face analysis node uses Insightface's buffalo_l model. This might be related to the observed differences.

When switching to DLib for feature point detection and using cosine to calculate similarity, for the same images, InstantID's value is higher than V2's, which aligns better with human intuition.
