### ISSUE TITLE
Having Issue with installation on Insightface Package

### ISSUE THREAD

**Issue by jimweaver** [shiimizu/ComfyUI-PhotoMaker-Plus#34]
Shiimizu, I'm facing this issue hopefully you can figure this out.

(IMPORT FAILED): C:\Art and Media\Data\Packages\ComfyUI\custom_nodes\ComfyUI-PhotoMaker-Plus

**_Message from console:_** 
>Loading: ComfyUI-Manager (V2.48.1)
ComfyUI Revision: 2474 [2d75df45] | Released on '2024-08-05'
Traceback (most recent call last):
  File "C:\Art and Media\Data\Packages\ComfyUI\nodes.py", line 1941, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Art and Media\Data\Packages\ComfyUI\custom_nodes\ComfyUI-PhotoMaker-Plus\__init__.py", line 1, in <module>
    from .photomaker import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "C:\Art and Media\Data\Packages\ComfyUI\custom_nodes\ComfyUI-PhotoMaker-Plus\photomaker.py", line 20, in <module>
    from .insightface_package import FaceAnalysis2, analyze_faces, insightface_loader
  File "C:\Art and Media\Data\Packages\ComfyUI\custom_nodes\ComfyUI-PhotoMaker-Plus\insightface_package.py", line 3, in <module>
    from insightface import FaceAnalysis
ModuleNotFoundError: No module named 'insightface'
Cannot import C:\Art and Media\Data\Packages\ComfyUI\custom_nodes\ComfyUI-PhotoMaker-Plus module for custom nodes: No module named 'insightface'

**_From cmd:_**
>pip check pydantic
confection 0.0.4 has requirement pydantic!=1.8,!=1.8.1,<1.11.0,>=1.7.4, but you have pydantic 2.7.0.
spacy 3.4.4 has requirement pydantic!=1.8,!=1.8.1,<1.11.0,>=1.7.4, but you have pydantic 2.7.0.
thinc 8.1.9 has requirement pydantic!=1.8,!=1.8.1,<1.11.0,>=1.7.4, but you have pydantic 2.7.0.

**Comment by jimweaver** [comment]
>pip check insightface
confection 0.0.4 has requirement pydantic!=1.8,!=1.8.1,<1.11.0,>=1.7.4, but you have pydantic 2.7.0.
spacy 3.4.4 has requirement pydantic!=1.8,!=1.8.1,<1.11.0,>=1.7.4, but you have pydantic 2.7.0.
thinc 8.1.9 has requirement pydantic!=1.8,!=1.8.1,<1.11.0,>=1.7.4, but you have pydantic 2.7.0.

**Comment by shiimizu** [comment]
Did you run
```bash
pip install -U insightface
```

**Comment by jimweaver** [comment]
Yeah, I already did. The version I have installed is 0.7.3.

**Comment by shiimizu** [comment]
It seems like many people have this issue[^1] [^2] [^3]. Make sure you use the `python` that runs ComfyUI.
So, something like `python_embeded\python.exe -m pip install -U insightface`

[^1]: [Dependencies missing for Insightface · Issue #162 · cubiq/ComfyUI_IPAdapter_plus (github.com)](https://zws.im/󠁭󠁮󠁷󠁡󠁱󠁹󠁿)

[^2]: [Installing Insightface : r/comfyui (reddit.com)](https://www.reddit.com/r/comfyui/comments/18qatfq/installing_insightface/)

[^3]: [Installing insightface... : r/comfyui (reddit.com)](https://www.reddit.com/r/comfyui/comments/18ou0ly/installing_insightface/)

There are also prebuilt packages so you don’t have to build it yourself:

[instructions](https://github.com/Gourieff/comfyui-reactor-node#i-for-windows-users-if-you-still-cannot-build-insightface-for-some-reasons-or-just-dont-want-to-install-visual-studio-or-vs-c-build-tools---do-the-following) from the reactor node.

[Instructions](https://www.reddit.com/r/comfyui/comments/18ou0ly/comment/kpb64e1/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button) from a reddit user:

>From the ComfyUI root folder (where you have "webui-user.bat" file) check the version of Python aka run CMD and type "python_embeded\python.exe -V"
> - Depending on Python version (3.10 or 3.11) download prebuilt Insightface package to ComfyUI root folder:  
> Python 3.10: [https://github.com/Gourieff/Assets/raw/main/Insightface/insightface-0.7.3-cp310-cp310-win_amd64.whl>](https://github.com/Gourieff/Assets/raw/main/Insightface/insightface-0.7.3-cp310-cp310-win_amd64.whl)  
> Python 3.11: [https://github.com/Gourieff/Assets/raw/main/Insightface/insightface-0.7.3-cp311-cp311-win_amd64.whl>](https://github.com/Gourieff/Assets/raw/main/Insightface/insightface-0.7.3-cp311-cp311-win_amd64.whl)
> - Install latest pip version: "`python_embeded\python.exe -m pip install -U pip`"
> - Install Insightface:  
Python 3.10: "`python_embeded\python.exe -m pip install insightface-0.7.3-cp310-cp310-win_amd64.whl`"  
Python 3.11: "`python_embeded\python.exe -m pip install insightface-0.7.3-cp311-cp311-win_amd64.whl`"

**Comment by jimweaver** [comment]
I'm using a launcher called Stability Matrix as a manager for ComfyUI. I'll go ahead and try to install insightface again.

**Comment by jimweaver** [comment]
Problem solved! I guess the Stability Matrix has it own python 3.10 env.

>I have follow the [https://github.com/Gourieff/comfyui-reactor-node#i-for-windows-users-if-you-still-cannot-build-insightface-for-some-reasons-or-just-dont-want-to-install-visual-studio-or-vs-c-build-tools---do-the-following](url) and downloaded prebuilt Insightface package into ComfyUI root folder in .venv/script through CMD 
> - python.exe -m pip install insightface

Finally, Stable Matrix is able to find insightface and install ComfyUI-PhotoMaker-Plus.
