### ISSUE TITLE
Could you tell me the reason to hook the default load？

### ISSUE THREAD

**Issue by allmelgr** [shiimizu/ComfyUI-PhotoMaker-Plus#37]
``` pyhton
def hook_load_torch_file():
    import comfy.utils
    if not hasattr(comfy.utils, 'load_torch_file_original'):
        comfy.utils.load_torch_file_original = comfy.utils.load_torch_file
    replace_str="""
    if sd.get('id_encoder', None) and (lora_weights:=sd.get('lora_weights', None)) and len(sd) == 2:
        def find_outer_instance(target:str, target_type):
            import inspect
            frame = inspect.currentframe()
            i = 0
            while frame and i < 5:
                if (found:=frame.f_locals.get(target, None)) is not None:
                    if isinstance(found, target_type):
                        return found
                frame = frame.f_back
                i += 1
            return None
        if find_outer_instance('lora_name', str) is not None:
            sd = lora_weights
    return sd"""
    source = inspect.getsource(comfy.utils.load_torch_file_original)
    modified_source = source.replace("return sd", replace_str)
    fn = write_to_file_and_return_fn(comfy.utils.load_torch_file_original, modified_source, 'w')
    return create_hook(fn, 'comfy.utils')
```

**Comment by allmelgr** [comment]
I'm not very familiar with Python, but this could lead to unpredictable consequences. 

1. After installing this plugin, it may cause an increase in memory usage because it requires loading LoRA , which wasn't necessary before.
2. If the ComfyUI code is updated, it might render the plugin unusable.

So, would it be better to add an additional node to load the model and LoRA separately?

**Comment by shiimizu** [comment]
Thank you for your feedback. I also do not like unnecessarily hooking into a function that's used throughout ComfyUI. I will remove it and make a new node probably called `PhotoMakerLoraLoader`.

**Comment by shiimizu** [comment]
Thank you for your feedback. I also do not like hooking into a function that's frequently used throughout ComfyUI when it can be avoided. I'll remove it and make a new node probably called PhotoMakerLoraLoader.

**Comment by Layer-norm** [comment]
It seems that your hook function has a conflict with my node.
You are not the only person who uses the **comfy.utils.load_torch_file** function.
When using my node, it would create a ".patch.py" file in your node folder, which means your node doesn't work as your except.
https://github.com/Layer-norm/ComfyUI-Taiyi/issues/1

**Comment by shiimizu** [comment]
@Layer-norm I will remove the hooks soon, but the issue you’re referring to is not related to this. That error means that person is missing the checkpoint/lora.
