### ISSUE TITLE
model_type Error

### ISSUE THREAD

**Issue by Xkipper** [shiimizu/ComfyUI-PhotoMaker-Plus#44]
I get the **model_type** error after update my _ComfyUI_ VER today...

```SH
!!! Exception during processing !!! 'model_type'
Traceback (most recent call last):
  File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-PhotoMaker-Plus\photomaker.py", line 44, in load_photomaker_model
    photomaker_model = PhotoMakerIDEncoder_CLIPInsightfaceExtendtoken()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-PhotoMaker-Plus\model_v2.py", line 135, in __init__
    super().__init__(VISION_CONFIG_DICT, dtype, offload_device, comfy.ops.manual_cast)
  File "F:\ComfyUI_windows_portable\ComfyUI\comfy\clip_model.py", line 209, in __init__
    self.vision_model = CLIPVision(config_dict, dtype, device, operations)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\ComfyUI\comfy\clip_model.py", line 182, in __init__
    model_type = config_dict["model_type"]
                 ~~~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'model_type'
```
**ComfyUI version :**
`ComfyUI Revision: 2846 [8f0009aa] *DETACHED | Released on '2024-11-21'`

```JS
CPU: 13th Gen Intel(R) Core(TM) i5-13600KF - Arch: AMD64 - OS: Windows 11
Pynvml (Nvidia) initialized.
GPU: NVIDIA GeForce RTX 4070 SUPER, VRAM 12282 MB
NVIDIA Driver: 566.14
Total RAM: 16215 MB
pytorch version: 2.5.1+cu124
Device: cuda:0 NVIDIA GeForce RTX 4070 SUPER : cudaMallocAsync
```

**Comment by the-xentropy** [comment]
It's due to the new FLUX update in ComfyUI which adds the model_type field to the CLIP vision configs, but this extension hardcodes its own variant which is now incompatible. Just roll comfy back or add a model_type entry (`"model_type": "clip_vision_model",`) in model_v2.py and/or model.py under the VISION_CONFIG_DICT dict. I can confirm that it works after making this trivial change.

I think this could be avoided in the future if the appropriate .json file from the comfy folder (e.g. comfy/clip_vision_config_vitl.json ) is loaded as a template rather than hardcoding the config values in the scripts as VISION_CONFIG_DICT.

**Comment by adgbit** [comment]
Hi @the-xentropy and @shiimizu I add ("model_type": "clip_vision_model",) in both file but still I'm getting that error, any hint or suggestion?

**Comment by popoleaf** [comment]
Mine too, the original workflow that ran through can't be used, it's too sad

**Comment by aqidesign** [comment]
> It's due to the new FLUX update in ComfyUI which adds the model_type field to the CLIP vision configs, but this extension hardcodes its own variant which is now incompatible. Just roll comfy back or add a model_type entry (`"model_type": "clip_vision_model",`) in model_v2.py and/or model.py under the VISION_CONFIG_DICT dict. I can confirm that it works after making this trivial change.这是由于 ComfyUI 中的新 FLUX 更新将 model_type 字段添加到 CLIP 视觉配置中，但此扩展硬编码了自己的变体，该变体现在不兼容。只需舒适地回滚或添加 model_type 条目（ `"model_type": "clip_vision_model",` ）在 VISION_CONFIG_DICT 字典下的 model_v2.py 和/或 model.py 中。我可以确认在进行这个微小的更改后它可以工作。
> 
> I think this could be avoided in the future if the appropriate .json file from the comfy folder (e.g. comfy/clip_vision_config_vitl.json ) is loaded as a template rather than hardcoding the config values in the scripts as VISION_CONFIG_DICT.我认为如果将 comfy 文件夹中的相应 .json 文件（例如 comfy/clip_vision_config_vitl.json ）作为模板加载，而不是将脚本中的配置值硬编码为 VISION_CONFIG_DICT，我认为将来可以避免这种情况。

thanks！It‘’s work.
