### ISSUE TITLE
it didn't look anything like reference images.

### ISSUE THREAD

**Issue by botnang** [shiimizu/ComfyUI-PhotoMaker-Plus#5]
input: 3 Photos (Asian face).
output: European face

![image](https://github.com/shiimizu/ComfyUI-PhotoMaker/assets/32015065/673dcae1-788e-41a9-82ed-88635888515e)

**Comment by bparrott78** [comment]
Same, it doesn't seem to do anything?

**Comment by Blucknote** [comment]
It seems like extension using only `ref_images_path`
When i use `ref_images_path` with correct samples it working as expected but source image can be even 
![olive-s-kolbasoj-1-kg](https://github.com/shiimizu/ComfyUI-PhotoMaker/assets/15163043/d05aca15-b02e-4953-a2e6-7ee136018bed)
which seem like unnecessary input on PhotoMaker Encode

**Comment by undavide** [comment]
Same here (M1 Mac), unless with `ref_images_path`, it's like not using it.

**Comment by Blucknote** [comment]
> I can confirm that [PR#6](https://github.com/shiimizu/ComfyUI-PhotoMaker/pull/6/files) fixes it!

Can confirm too

**Comment by ronaldomirandah** [comment]
Is not working for me too, the output image has nothing to do with input images. Is this really working?

**Comment by shiimizu** [comment]
Closing this since I think it's been fixed. If it hasn't, let me know.
