### ISSUE TITLE
Conflict issue with the repository name.

### ISSUE THREAD

**Issue by ltdrdata** [shiimizu/ComfyUI-PhotoMaker-Plus#9]
There is already an existing repository with the same name "ComfyUI-PhotoMaker." 

https://github.com/ZHO-ZHO-ZHO/ComfyUI-PhotoMaker

This may cause confusion in the future in various ways.
It is recommended to change the repository name.

**Comment by Aamir3d** [comment]
Seconded. Please change the repository name. I wanted to try out your repo too, but have not been able to because of conflicts.

**Comment by shiimizu** [comment]
I have that extension installed as reference. You can install both repos if you rename the folders.
`git clone https://github.com/ZHO-ZHO-ZHO/ComfyUI-PhotoMaker.git ComfyUI-PhotoMaker-ZHO`
I don't want to to change the repo name because this is the ComfyUI implementation, while the rest are wrappers over `diffusers`.

**Comment by Aamir3d** [comment]
Thanks - I already had that installed before, so I renamed your repo :-) . Looking forward to trying out your implementation.

**Comment by hben35096** [comment]
> Seconded. Please change the repository name. I wanted to try out your repo too, but have not been able to because of conflicts.
I'd also like to try it, do I need to download the model file for 38G now?

**Comment by Aamir3d** [comment]
> > Seconded. Please change the repository name. I wanted to try out your repo too, but have not been able to because of conflicts.
> 
> I'd also like to try it, do I need to download the model file for 38G now?

The Photomaker.bin is ~1GB

**Comment by hben35096** [comment]
In the .cachehuggingfacehub directory, is there no need to cache RealVisXL_V3.0?
